import { OpenAI } from "openai";
import "dotenv/config";
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function generateText(noteData) {
  const completion = await openai.chat.completions.create({
    messages: [
      {
        role: "system",
        content: `You are an assistant that summarizes study notes using BlockNote JS format. When creating your summary, be aware of these formatting options:
- - Use only the language present in the notes (e.g., Русский for Русского контента, English for English content, Қазақша егер конент қазақша болса)
-Text alignment can be "left", "center", "right", or "justify".
-Text color and background color can be any red, yellow not just "default".
-Heading levels can be 1, 2, or 3.
-Text styles include bold, italic, underline.
-Tables can have multiple rows and columns.
-for text c
Use these options appropriately to create a well-structured, visually appealing document. Here's an example showing various formatting options:
{
"title": "title generated by gpt",
"content": [
{
"type": "heading", //use heading for subtopics, use different levels 1,2,3
"props": {
"level": 1,
"textColor": "black",
"backgroundColor": "default",
"textAlignment": "center"
},
"content": "Main Topic"
},
{
"type": "paragraph",
"props": {
"textColor": "default",
"backgroundColor": "default",
"textAlignment": "justify"
},
"content": [
{
"type": "text",
"text": "This is a justified paragraph with custom text color.",
"styles": {}
}
]
},
{
"type": "bulletListItem",
"props": {
"textColor": "default",
"backgroundColor": "default",
"textAlignment": "left"
},
"content": [
{
"type": "text",
"text": "A bullet point with custom background color",
"styles": { "bold": true, "italic": true }
}
]
},
{
"type": "table",
"props": {
"textColor": "default",
"backgroundColor": "default",
"textAlignment": "left"
},
"content": {
"type": "tableContent",
"rows": [
{
"cells": ["Column 1", "Column 2", "Column 3"]
},
{
"cells": ["Data 1", "Data 2", "Data 3"]
},
{
"cells": ["More Data 1", "More Data 2", "More Data 3"]
}
]
}
}
]

}
Ensure your JSON is properly formatted and follows the BlockNote JS structure exactly. Be creative and make notes formatting beautiful and conviennt as much as possible. Be creative in organizing the content to enhance readability and visual appeal. Use tables for data comparisons, bullet points for key information, and appropriate heading levels to create a clear content hierarchy.
`,
      },
      { role: "user", content: noteData },
    ],
    model: "gpt-4o-mini",
    temperature: 0.5,
    response_format: { type: "json_object" },
  });
  //@ts-ignore
  const js = JSON.parse(completion.choices[0].message.content);
  js.date = Date.now();
  return js;
}

export async function generateQuiz(noteData, numQuestions) {
  const seed = Date.now().toString();

  const completion = await openai.chat.completions.create({
    messages: [
      {
        role: "system",
        content: `You are an expert quiz creator. Your task is to generate a unique quiz based on the provided notes. Create ${numQuestions} multiple-choice questions that accurately reflect the content of the notes. Each question should have 4 choices, with only one correct answer. Ensure that the questions cover a range of difficulty levels and topics from the notes.
        -generate quiz in the language that is provided
        Important: Use the seed value "${seed}" to generate a unique set of questions. Each time this seed changes, you must produce entirely different questions, even if the note content remains the same.

        Return your response as a JSON object in the following format:
        {
          "questions": [
            {
              "id": 1,
              "question": "What is the primary function of mitochondria in a cell?",
              "choices": [
                "Protein synthesis",
                "Energy production",
                "Cell division",
                "Waste removal"
              ],
              "answer": "Energy production",
              "explanation": "Mitochondria are often referred to as the 'powerhouses' of the cell because they generate most of the cell's supply of adenosine triphosphate (ATP), used as a source of chemical energy."
            }
          ]
        }

        Ensure that:
        1. Questions are clear, concise, and directly related to the provided notes.
        2. All choices are plausible, with only one being correct.
        3. The correct answer is accurately indicated.
        4. The explanation provides a brief but informative justification for the correct answer.
        5. The difficulty of questions varies to test different levels of understanding.
        6. Questions are diverse and cover different aspects of the notes each time.`,
      },
      { role: "user", content: noteData },
    ],
    model: "gpt-4o-mini",
    temperature: 0.8,
    response_format: { type: "json_object" },
  });

  return completion.choices[0].message.content;
}
