import { OpenAI } from "openai";
import "dotenv/config";
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function generateText(data) {
  const completion = await openai.chat.completions.create({
    messages: [
      {
        role: "system",
        content: `You are a helpful assistant that summarizes the  notes. Summarize and organize the following collection of study notes from a screen recording session. Please format the summary in Markdown, creating a well-structured, easy-to-review document:
            - Begin with a brief overview of the main topics covered
            - Organize the content into logical sections and subsections
            - Use appropriate Markdown headings (# for main sections, ## for subsections, etc.)
            - Utilize bullet points and numbered lists for clarity
            - Include any important formulas, equations, or code snippets in appropriate code blocks
            - Create tables if they would help organize related information
            - Bold key terms or important concepts
            - Use italics for emphasis where appropriate
            - If applicable, include a brief "Key Takeaways" section at the end
        Aim to create a comprehensive yet concise summary that captures the essence of the study session. The final document should be well-organized, visually appealing, and effective for review purposes.
        If you notice any gaps in the information or areas that seem to lack context, please note these at the end of the summary as "Potential areas for further study".:
        ALWAYS return in JSON fromat
        {
          "title": "title generated by gpt",
          "content": "notes generated by gpt"
        }`,
      },
      { role: "user", content: data },
    ],
    model: "gpt-4o",
    temperature: 0.5,
    response_format: { type: "json_object" },
  });
  return completion.choices[0].message.content;
}
