/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0eZ4KCrvReC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-gradient-to-r from-[#0072C6] to-[#005A9E] text-white py-4 px-6 flex items-center justify-between shadow-md">
        <div className="flex items-center gap-4">
          <Link href="#" className="text-lg font-semibold" prefetch={false}>
            <div className="flex items-center gap-2">
              <VideoIcon className="w-6 h-6 animate-pulse" />
              Screen Recorder
            </div>
          </Link>
        </div>
        <div className="flex items-center gap-4">
          <Button
            variant="secondary"
            className="px-4 py-2 bg-[#6b7280] text-white hover:bg-[#4b5563] transition-colors duration-300 rounded-full shadow-lg"
          >
            Sign In
          </Button>
          <Button className="px-4 py-2 bg-gradient-to-r from-[#0072C6] to-[#005A9E] text-white hover:from-[#005A9E] hover:to-[#0072C6] transition-colors duration-300 rounded-full shadow-lg">
            Sign Up
          </Button>
        </div>
      </header>
      <main className="flex-1 relative">
        <div className="absolute inset-0 bg-[url('/placeholder.svg')] bg-cover bg-center opacity-20 z-0" />
        <div className="relative max-w-3xl mx-auto flex flex-col items-center gap-8 p-6 md:p-10">
          <div className="bg-[#334155] rounded-lg shadow-2xl p-6 w-full flex flex-col items-center gap-4 animate-fade-in">
            <div className="flex items-center gap-4">
              <div className="bg-gradient-to-br from-[#374151] to-[#4b5563] rounded-full w-12 h-12 flex items-center justify-center shadow-lg">
                <VideoIcon className="w-6 h-6 text-white animate-pulse" />
              </div>
              <h2 className="text-2xl font-bold text-white">Screen Recorder</h2>
            </div>
            <div className="flex items-center gap-4">
              <Button
                className="px-6 py-3 bg-gradient-to-r from-[#0072C6] to-[#005A9E] text-white hover:from-[#005A9E] hover:to-[#0072C6] transition-colors duration-300 rounded-full shadow-2xl"
                id="start-button"
              >
                Start
              </Button>
              <Button
                className="px-6 py-3 bg-gradient-to-r from-[#0072C6] to-[#005A9E] text-white hover:from-[#005A9E] hover:to-[#0072C6] transition-colors duration-300 rounded-full shadow-2xl hidden"
                id="stop-button"
              >
                Stop
              </Button>
            </div>
          </div>
          <div className="bg-[#334155] rounded-lg shadow-2xl p-6 w-full animate-fade-in">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-bold text-white">Recent Notes</h3>
              <div className="flex gap-4">
                <Button
                  variant="secondary"
                  className="px-4 py-2 bg-[#6b7280] text-white hover:bg-[#4b5563] transition-colors duration-300 rounded-full shadow-lg"
                >
                  See All Notes
                </Button>
              </div>
            </div>
            <div className="flex gap-4 overflow-x-auto pb-4">
              <Card className="flex-shrink-0 w-64 bg-[#334155] text-white shadow-2xl hover:shadow-lg transition-shadow duration-300 rounded-2xl">
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="bg-[#475569] rounded-full w-8 h-8 flex items-center justify-center shadow-lg">
                      <CalendarIcon className="w-5 h-5 text-[#94a3b8] animate-pulse" />
                    </div>
                    <div className="text-sm text-[#94a3b8]">Aug 24, 2023</div>
                  </div>
                  <h4 className="text-lg font-bold mb-2">Recorded screen session</h4>
                  <p className="text-sm text-[#94a3b8]">
                    Recorded a 15-minute screen session and took notes on the key points.
                  </p>
                </CardContent>
              </Card>
              <Card className="flex-shrink-0 w-64 bg-[#334155] text-white shadow-2xl hover:shadow-lg transition-shadow duration-300 rounded-2xl">
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="bg-[#475569] rounded-full w-8 h-8 flex items-center justify-center shadow-lg">
                      <CalendarIcon className="w-5 h-5 text-[#94a3b8] animate-pulse" />
                    </div>
                    <div className="text-sm text-[#94a3b8]">Aug 22, 2023</div>
                  </div>
                  <h4 className="text-lg font-bold mb-2">Brainstorming session</h4>
                  <p className="text-sm text-[#94a3b8]">
                    Recorded a 30-minute brainstorming session and captured the key ideas.
                  </p>
                </CardContent>
              </Card>
              <Card className="flex-shrink-0 w-64 bg-[#334155] text-white shadow-2xl hover:shadow-lg transition-shadow duration-300 rounded-2xl">
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="bg-[#475569] rounded-full w-8 h-8 flex items-center justify-center shadow-lg">
                      <CalendarIcon className="w-5 h-5 text-[#94a3b8] animate-pulse" />
                    </div>
                    <div className="text-sm text-[#94a3b8]">Aug 20, 2023</div>
                  </div>
                  <h4 className="text-lg font-bold mb-2">Product demo</h4>
                  <p className="text-sm text-[#94a3b8]">
                    Recorded a 20-minute product demo and took notes on the key features.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
          <div className="bg-[#334155] rounded-lg shadow-2xl p-6 w-full animate-fade-in">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-bold text-white">How It Works</h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-[#475569] rounded-lg p-4 shadow-lg">
                <div className="flex items-center gap-4 mb-4">
                  <div className="bg-gradient-to-br from-[#374151] to-[#4b5563] rounded-full w-12 h-12 flex items-center justify-center shadow-lg">
                    <VideoIcon className="w-6 h-6 text-white animate-pulse" />
                  </div>
                  <h4 className="text-lg font-bold text-white">Record</h4>
                </div>
                <p className="text-sm text-[#94a3b8]">Click the "Start" button to begin recording your screen.</p>
              </div>
              <div className="bg-[#475569] rounded-lg p-4 shadow-lg">
                <div className="flex items-center gap-4 mb-4">
                  <div className="bg-gradient-to-br from-[#374151] to-[#4b5563] rounded-full w-12 h-12 flex items-center justify-center shadow-lg">
                    <StickyNoteIcon className="w-6 h-6 text-white animate-pulse" />
                  </div>
                  <h4 className="text-lg font-bold text-white">Take Notes</h4>
                </div>
                <p className="text-sm text-[#94a3b8]">
                  While recording, you can take notes on the key points of your session.
                </p>
              </div>
              <div className="bg-[#475569] rounded-lg p-4 shadow-lg">
                <div className="flex items-center gap-4 mb-4">
                  <div className="bg-gradient-to-br from-[#374151] to-[#4b5563] rounded-full w-12 h-12 flex items-center justify-center shadow-lg">
                    <SaveIcon className="w-6 h-6 text-white animate-pulse" />
                  </div>
                  <h4 className="text-lg font-bold text-white">Save</h4>
                </div>
                <p className="text-sm text-[#94a3b8]">
                  When you're done, click the "Stop" button to save your recording and notes.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function SaveIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z" />
      <path d="M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7" />
      <path d="M7 3v4a1 1 0 0 0 1 1h7" />
    </svg>
  )
}


function StickyNoteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8Z" />
      <path d="M15 3v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}


function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
